version: '3'
services:
  solr:
    build:
      context: ./solr
    ports:
      - 8983:8983
    volumes:
      - solr-data:/opt/solr/server/solr/ckan/data
    command: solr-create -c vivocore -d /opt/vivocore

  vivo:
    build:
      context: ./vivo
    volumes:
      - ./example-config:/usr/local/vivo/home/config
    ports:
      - 8080:8080


volumes:
  solr-data:
